// Speakability - Final Year Project
// Author: Andrew Raynes
// Tutor: Baihua Li
// Developed from October 2013 to March 2014


#import "AnimationViewController.h"

@interface AnimationViewController ()

@end

@implementation AnimationViewController
@synthesize playExerciseSound;
@synthesize exercise1Button;
@synthesize exercise1;
@synthesize exercise2Button;
@synthesize exercise2;
@synthesize exercise3Button;
@synthesize exercise3;
@synthesize exercise4Button;
@synthesize exercise4;
@synthesize exercise5Button;
@synthesize exercise5;
@synthesize exercise6Button;
@synthesize exercise6;
@synthesize exercise7Button;
@synthesize exercise7;
@synthesize exercise8Button;
@synthesize exercise8;
@synthesize exercise9Button;
@synthesize exercise9;

- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view, typically from a nib.
    
    
    //Exercise Sound
    NSURL *buttonURL = [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"Exercise_Sound" ofType:@"wav"]];
    AudioServicesCreateSystemSoundID((__bridge CFURLRef)buttonURL, &SoundID);

    //setup animation
    NSMutableArray *exercise1array = [[NSMutableArray alloc] initWithObjects:
                                      @"facetest0001.png",
                                      @"facetest0002.png",
                                      @"facetest0003.png",
                                      @"facetest0004.png",
                                      @"facetest0005.png",
                                      @"facetest0006.png",
                                      @"facetest0007.png",
                                      @"facetest0008.png",
                                      @"facetest0009.png",
                                      @"facetest0010.png",
                                      @"facetest0011.png",
                                      @"facetest0012.png",
                                      @"facetest0013.png",
                                      @"facetest0014.png",
                                      @"facetest0015.png",
                                      @"facetest0016.png",
                                      @"facetest0017.png",
                                      @"facetest0018.png",
                                      @"facetest0019.png",
                                      @"facetest0020.png",
                                      @"facetest0021.png",
                                      @"facetest0022.png",
                                      @"facetest0023.png",
                                      @"facetest0024.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0025.png",
                                      @"facetest0024.png",
                                      @"facetest0023.png",
                                      @"facetest0022.png",
                                      @"facetest0021.png",
                                      @"facetest0020.png",
                                      @"facetest0019.png",
                                      @"facetest0018.png",
                                      @"facetest0017.png",
                                      @"facetest0016.png",
                                      @"facetest0015.png",
                                      @"facetest0014.png",
                                      @"facetest0013.png",
                                      @"facetest0012.png",
                                      @"facetest0011.png",
                                      @"facetest0010.png",
                                      @"facetest0009.png",
                                      @"facetest0008.png",
                                      @"facetest0007.png",
                                      @"facetest0006.png",
                                      @"facetest0005.png",
                                      @"facetest0004.png",
                                      @"facetest0003.png",
                                      @"facetest0002.png",
                                      @"facetest0001.png",
                                      nil];
    //[exercise1 setAnimationImages: exercise1array previewFirstFrame:YES];
    exercise1.animationImages = exercise1array;
    exercise1.animationDuration = 7.0;
    exercise1.animationRepeatCount = 1;
    exercise1array = nil;
    
    
    
    //Exercise 2 Array
    NSMutableArray *exercise2array = [[NSMutableArray alloc] initWithObjects:
                                      @"facetest0325",
                                      @"facetest0324",
                                      @"facetest0323",
                                      @"facetest0322",
                                      @"facetest0321",
                                      @"facetest0320",
                                      @"facetest0319",
                                      @"facetest0318",
                                      @"facetest0317",
                                      @"facetest0316",
                                      @"facetest0315",
                                      @"facetest0314",
                                      @"facetest0313",
                                      @"facetest0312",
                                      @"facetest0311",
                                      @"facetest0310",
                                      @"facetest0309",
                                      @"facetest0308",
                                      @"facetest0307",
                                      @"facetest0306",
                                      @"facetest0305",
                                      @"facetest0304",
                                      @"facetest0303",
                                      @"facetest0302",
                                      @"facetest0301",
                                      @"facetest0300",
                                      @"facetest0299",
                                      @"facetest0298",
                                      @"facetest0297",
                                      @"facetest0296",
                                      @"facetest0295",
                                      @"facetest0294",
                                      @"facetest0293",
                                      @"facetest0292",
                                      @"facetest0291",
                                      @"facetest0290",
                                      @"facetest0289",
                                      @"facetest0288",
                                      @"facetest0287",
                                      @"facetest0286",
                                      @"facetest0285",
                                      @"facetest0284",
                                      @"facetest0283",
                                      @"facetest0282",
                                      @"facetest0281",
                                      @"facetest0280",
                                      @"facetest0279",
                                      @"facetest0278",
                                      @"facetest0277",
                                      @"facetest0276",
                                      @"facetest0275",
                                      @"facetest0274",
                                      @"facetest0273",
                                      @"facetest0272",
                                      @"facetest0271",
                                      @"facetest0270",
                                      @"facetest0269",
                                      @"facetest0268",
                                      @"facetest0267",
                                      @"facetest0266",
                                      @"facetest0265",
                                      @"facetest0264",
                                      @"facetest0263",
                                      @"facetest0262",
                                      @"facetest0261",
                                      @"facetest0260",
                                      @"facetest0259",
                                      @"facetest0258",
                                      @"facetest0257",
                                      @"facetest0256",
                                      @"facetest0255",
                                      @"facetest0254",
                                      @"facetest0253",
                                      @"facetest0252",
                                      @"facetest0251",
                                      @"facetest0250",
                                      @"facetest0249",
                                      @"facetest0248",
                                      @"facetest0247",
                                      @"facetest0246",
                                      @"facetest0245",
                                      @"facetest0244",
                                      @"facetest0243",
                                      @"facetest0242",
                                      @"facetest0241",
                                      @"facetest0240",
                                      @"facetest0239",
                                      @"facetest0238",
                                      @"facetest0237",
                                      @"facetest0236",
                                      @"facetest0235",
                                      @"facetest0234",
                                      @"facetest0233",
                                      @"facetest0232",
                                      @"facetest0231",
                                      @"facetest0230",
                                      @"facetest0229",
                                      @"facetest0228",
                                      @"facetest0227",
                                      @"facetest0226",
                                      @"facetest0225",
                                      @"facetest0224",
                                      @"facetest0223",
                                      @"facetest0222",
                                      @"facetest0221",
                                      @"facetest0220",
                                      @"facetest0219",
                                      @"facetest0218",
                                      @"facetest0217",
                                      @"facetest0216",
                                      @"facetest0215",
                                      @"facetest0214",
                                      @"facetest0213",
                                      @"facetest0212",
                                      @"facetest0211",
                                      @"facetest0210",
                                      @"facetest0209",
                                      @"facetest0208",
                                      @"facetest0207",
                                      @"facetest0206",
                                      @"facetest0205",
                                      @"facetest0204",
                                      @"facetest0203",
                                      @"facetest0202",
                                      @"facetest0201",
                                      @"facetest0200",
                                      @"facetest0199",
                                      @"facetest0198",
                                      @"facetest0197",
                                      @"facetest0196",
                                      @"facetest0195",
                                      @"facetest0194",
                                      @"facetest0193",
                                      @"facetest0192",
                                      @"facetest0191",
                                      @"facetest0190",
                                      @"facetest0189",
                                      @"facetest0188",
                                      @"facetest0187",
                                      @"facetest0186",
                                      @"facetest0185",
                                      @"facetest0184",
                                      @"facetest0183",
                                      @"facetest0182",
                                      @"facetest0181",
                                      @"facetest0180",
                                      @"facetest0179",
                                      @"facetest0178",
                                      @"facetest0177",
                                      @"facetest0176",
                                      @"facetest0175",
                                      @"facetest0300",
                                      @"facetest0301",
                                      @"facetest0302",
                                      @"facetest0303",
                                      @"facetest0304",
                                      @"facetest0305",
                                      @"facetest0306",
                                      @"facetest0307",
                                      @"facetest0308",
                                      @"facetest0309",
                                      @"facetest0310",
                                      @"facetest0311",
                                      @"facetest0312",
                                      @"facetest0313",
                                      @"facetest0314",
                                      @"facetest0315",
                                      @"facetest0316",
                                      @"facetest0317",
                                      @"facetest0318",
                                      @"facetest0319",
                                      @"facetest0320",
                                      @"facetest0321",
                                      @"facetest0322",
                                      @"facetest0323",
                                      @"facetest0324",
                                      @"facetest0325",
                                      nil];
    exercise2.animationImages = exercise2array;
    exercise2.animationDuration = 7.0;
    exercise2.animationRepeatCount = 1;

    //Exercise 3 Array
    NSMutableArray *exercise3array = [[NSMutableArray alloc] initWithObjects:
                                      @"facetest0350.png",
                                      @"facetest0351.png",
                                      @"facetest0352.png",
                                      @"facetest0353.png",
                                      @"facetest0354.png",
                                      @"facetest0355.png",
                                      @"facetest0356.png",
                                      @"facetest0357.png",
                                      @"facetest0358.png",
                                      @"facetest0359.png",
                                      @"facetest0360.png",
                                      @"facetest0361.png",
                                      @"facetest0362.png",
                                      @"facetest0363.png",
                                      @"facetest0364.png",
                                      @"facetest0365.png",
                                      @"facetest0366.png",
                                      @"facetest0367.png",
                                      @"facetest0368.png",
                                      @"facetest0369.png",
                                      @"facetest0370.png",
                                      @"facetest0371.png",
                                      @"facetest0372.png",
                                      @"facetest0373.png",
                                      @"facetest0374.png",
                                      @"facetest0375.png",
                                      @"facetest0376.png",
                                      @"facetest0377.png",
                                      @"facetest0378.png",
                                      @"facetest0379.png",
                                      @"facetest0380.png",
                                      @"facetest0381.png",
                                      @"facetest0382.png",
                                      @"facetest0383.png",
                                      @"facetest0384.png",
                                      @"facetest0385.png",
                                      @"facetest0386.png",
                                      @"facetest0387.png",
                                      @"facetest0388.png",
                                      @"facetest0389.png",
                                      @"facetest0391.png",
                                      @"facetest0392.png",
                                      @"facetest0393.png",
                                      @"facetest0394.png",
                                      @"facetest0395.png",
                                      @"facetest0396.png",
                                      @"facetest0397.png",
                                      @"facetest0398.png",
                                      @"facetest0399.png",
                                      @"facetest0400.png",
                                      @"facetest0401.png",
                                      @"facetest0402.png",
                                      @"facetest0403.png",
                                      @"facetest0404.png",
                                      @"facetest0405.png",
                                      @"facetest0406.png",
                                      @"facetest0407.png",
                                      @"facetest0408.png",
                                      @"facetest0408.png",
                                      @"facetest0410.png",
                                      @"facetest0411.png",
                                      @"facetest0412.png",
                                      @"facetest0413.png",
                                      @"facetest0414.png",
                                      @"facetest0415.png",
                                      @"facetest0416.png",
                                      @"facetest0417.png",
                                      @"facetest0418.png",
                                      @"facetest0419.png",
                                      @"facetest0420.png",
                                      @"facetest0421.png",
                                      @"facetest0422.png",
                                      @"facetest0423.png",
                                      @"facetest0424.png",
                                      @"facetest0425.png",
                                      @"facetest0426.png",
                                      @"facetest0427.png",
                                      @"facetest0428.png",
                                      @"facetest0429.png",
                                      @"facetest0430.png",
                                      @"facetest0431.png",
                                      @"facetest0432.png",
                                      @"facetest0433.png",
                                      @"facetest0434.png",
                                      @"facetest0435.png",
                                      @"facetest0436.png",
                                      @"facetest0437.png",
                                      @"facetest0438.png",
                                      @"facetest0439.png",
                                      @"facetest0440.png",
                                      @"facetest0441.png",
                                      @"facetest0442.png",
                                      @"facetest0443.png",
                                      @"facetest0444.png",
                                      @"facetest0445.png",
                                      @"facetest0446.png",
                                      @"facetest0447.png",
                                      @"facetest0448.png",
                                      @"facetest0449.png",
                                      @"facetest0450.png",
                                      @"facetest0451.png",
                                      @"facetest0452.png",
                                      @"facetest0453.png",
                                      @"facetest0454.png",
                                      @"facetest0455.png",
                                      @"facetest0456.png",
                                      @"facetest0457.png",
                                      @"facetest0458.png",
                                      @"facetest0459.png",
                                      @"facetest0460.png",
                                      @"facetest0461.png",
                                      @"facetest0462.png",
                                      @"facetest0463.png",
                                      @"facetest0464.png",
                                      @"facetest0465.png",
                                      @"facetest0466.png",
                                      @"facetest0467.png",
                                      @"facetest0468.png",
                                      @"facetest0469.png",
                                      @"facetest0470.png",
                                      @"facetest0471.png",
                                      @"facetest0472.png",
                                      @"facetest0473.png",
                                      @"facetest0474.png",
                                      @"facetest0475.png",
                                      @"facetest0476.png",
                                      @"facetest0477.png",
                                      @"facetest0478.png",
                                      @"facetest0479.png",
                                      @"facetest0480.png",
                                      @"facetest0481.png",
                                      @"facetest0482.png",
                                      @"facetest0483.png",
                                      @"facetest0484.png",
                                      @"facetest0485.png",
                                      @"facetest0486.png",
                                      @"facetest0487.png",
                                      @"facetest0488.png",
                                      @"facetest0489.png",
                                      @"facetest0490.png",
                                      @"facetest0491.png",
                                      @"facetest0492.png",
                                      @"facetest0493.png",
                                      @"facetest0494.png",
                                      @"facetest0495.png",
                                      @"facetest0496.png",
                                      @"facetest0497.png",
                                      @"facetest0498.png",
                                      @"facetest0499.png",
                                      @"facetest0500.png",
                                      @"facetest0501.png",
                                      @"facetest0502.png",
                                      @"facetest0503.png",
                                      @"facetest0504.png",
                                      @"facetest0505.png",
                                      @"facetest0506.png",
                                      @"facetest0507.png",
                                      @"facetest0508.png",
                                      @"facetest0509.png",
                                      @"facetest0510.png",
                                      @"facetest0511.png",
                                      @"facetest0512.png",
                                      @"facetest0513.png",
                                      @"facetest0514.png",
                                      nil];
    //[exercise3 setAnimationImages: exercise3array previewFirstFrame:YES];
    exercise3.animationImages = exercise3array;
    exercise3.animationDuration = 6.56;
    exercise3.animationRepeatCount = 1;
    exercise3array = nil;

    
    //Exercise 4 Array
   NSMutableArray *exercise4array = [[NSMutableArray alloc] initWithObjects:
                                     @"facetest0549",
                                     @"facetest0550",
                                     @"facetest0551",
                                     @"facetest0552",
                                     @"facetest0553",
                                     @"facetest0554",
                                     @"facetest0555",
                                     @"facetest0556",
                                     @"facetest0557",
                                     @"facetest0558",
                                     @"facetest0559",
                                     @"facetest0560",
                                     @"facetest0561",
                                     @"facetest0562",
                                     @"facetest0563",
                                     @"facetest0564",
                                     @"facetest0565",
                                     @"facetest0566",
                                     @"facetest0567",
                                     @"facetest0568",
                                     @"facetest0569",
                                     @"facetest0570",
                                     @"facetest0571",
                                     @"facetest0572",
                                     @"facetest0573",
                                     @"facetest0574",
                                     @"facetest0575",
                                     @"facetest0576",
                                     @"facetest0577",
                                     @"facetest0578",
                                     @"facetest0579",
                                     @"facetest0580",
                                     @"facetest0581",
                                     @"facetest0582",
                                     @"facetest0583",
                                     @"facetest0584",
                                     @"facetest0585",
                                     @"facetest0586",
                                     @"facetest0587",
                                     @"facetest0588",
                                     @"facetest0589",
                                     @"facetest0590",
                                     @"facetest0591",
                                     @"facetest0592",
                                     @"facetest0593",
                                     @"facetest0594",
                                     @"facetest0595",
                                     @"facetest0596",
                                     @"facetest0597",
                                     @"facetest0598",
                                     @"facetest0599",
                                     @"facetest0600",
                                     @"facetest0601",
                                     @"facetest0602",
                                     @"facetest0603",
                                     @"facetest0604",
                                     @"facetest0605",
                                     @"facetest0606",
                                     @"facetest0607",
                                     @"facetest0608",
                                     @"facetest0609",
                                     @"facetest0610",
                                     @"facetest0611",
                                     @"facetest0612",
                                     @"facetest0613",
                                     @"facetest0614",
                                     @"facetest0615",
                                     @"facetest0616",
                                     @"facetest0617",
                                     @"facetest0618",
                                     @"facetest0619",
                                     @"facetest0620",
                                     @"facetest0621",
                                     @"facetest0622",
                                     @"facetest0623",
                                     @"facetest0624",
                                     @"facetest0625",
                                     @"facetest0626",
                                     @"facetest0627",
                                     @"facetest0628",
                                     @"facetest0629",
                                     @"facetest0630",
                                     @"facetest0631",
                                     @"facetest0632",
                                     @"facetest0633",
                                     @"facetest0634",
                                     @"facetest0635",
                                     @"facetest0636",
                                     @"facetest0637",
                                     @"facetest0638",
                                     @"facetest0639",
                                     @"facetest0640",
                                     @"facetest0641",
                                     @"facetest0642",
                                     @"facetest0643",
                                     @"facetest0644",
                                     @"facetest0645",
                                     @"facetest0646",
                                     @"facetest0647",
                                     @"facetest0648",
                                     @"facetest0649",
                                     @"facetest0650",
                                     @"facetest0651",
                                     @"facetest0652",
                                     @"facetest0653",
                                     @"facetest0654",
                                     @"facetest0655",
                                     @"facetest0656",
                                     @"facetest0657",
                                     @"facetest0658",
                                     @"facetest0659",
                                     @"facetest0660",
                                     @"facetest0661",
                                     @"facetest0662",
                                     @"facetest0663",
                                     @"facetest0664",
                                     @"facetest0665",
                                     @"facetest0666",
                                     @"facetest0667",
                                     @"facetest0668",
                                     @"facetest0669",
                                     @"facetest0670",
                                     @"facetest0671",
                                     @"facetest0672",
                                     @"facetest0673",
                                     @"facetest0674",
                                     @"facetest0675",
                                     @"facetest0676",
                                     @"facetest0677",
                                     @"facetest0678",
                                     @"facetest0679",
                                     @"facetest0680",
                                     @"facetest0681",
                                     @"facetest0682",
                                     @"facetest0683",
                                     @"facetest0684",
                                     @"facetest0685",
                                     @"facetest0686",
                                     @"facetest0687",
                                     @"facetest0688",
                                     @"facetest0689",
                                     @"facetest0690",
                                     @"facetest0691",
                                     @"facetest0692",
                                     @"facetest0693",
                                     @"facetest0694",
                                     @"facetest0695",
                                     @"facetest0696",
                                     @"facetest0697",
                                     @"facetest0698",
                                     @"facetest0699",
                                     @"facetest0573",
                                     @"facetest0572",
                                     @"facetest0571",
                                     @"facetest0570",
                                     @"facetest0569",
                                     @"facetest0568",
                                     @"facetest0567",
                                     @"facetest0566",
                                     @"facetest0565",
                                     @"facetest0564",
                                     @"facetest0563",
                                     @"facetest0562",
                                     @"facetest0561",
                                     @"facetest0560",
                                     @"facetest0559",
                                     @"facetest0558",
                                     @"facetest0557",
                                     @"facetest0556",
                                     @"facetest0555",
                                     @"facetest0554",
                                     @"facetest0553",
                                     @"facetest0552",
                                     @"facetest0551",
                                     @"facetest0550",
                                     @"facetest0549",
                                     nil];
    exercise4.animationImages = exercise4array;
    exercise4.animationDuration = 6.96;
    exercise4.animationRepeatCount = 1;
    exercise2array = nil;
    
    
    //Exercise 5 Array
    NSMutableArray *exercise5array = [[NSMutableArray alloc] initWithObjects:
                                      @"fishface0001",
                                      @"fishface0002",
                                      @"fishface0003",
                                      @"fishface0004",
                                      @"fishface0005",
                                      @"fishface0006",
                                      @"fishface0007",
                                      @"fishface0008",
                                      @"fishface0009",
                                      @"fishface0010",
                                      @"fishface0011",
                                      @"fishface0012",
                                      @"fishface0013",
                                      @"fishface0014",
                                      @"fishface0015",
                                      @"fishface0016",
                                      @"fishface0017",
                                      @"fishface0018",
                                      @"fishface0019",
                                      @"fishface0020",
                                      @"fishface0021",
                                      @"fishface0022",
                                      @"fishface0023",
                                      @"fishface0024",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0025",
                                      @"fishface0026",
                                      @"fishface0027",
                                      @"fishface0028",
                                      @"fishface0029",
                                      @"fishface0030",
                                      @"fishface0031",
                                      @"fishface0032",
                                      @"fishface0033",
                                      @"fishface0034",
                                      @"fishface0035",
                                      @"fishface0036",
                                      @"fishface0037",
                                      @"fishface0038",
                                      @"fishface0039",
                                      @"fishface0040",
                                      @"fishface0041",
                                      @"fishface0042",
                                      @"fishface0043",
                                      @"fishface0044",
                                      @"fishface0045",
                                      @"fishface0046",
                                      @"fishface0047",
                                      @"fishface0048",
                                      @"fishface0049",
                                      @"fishface0050",
                                      nil];
    exercise5.animationImages = exercise5array;
    exercise5.animationDuration = 7.0;
    exercise5.animationRepeatCount = 1;
    exercise5array = nil;

    //Exercise 6 Array
    NSMutableArray *exercise6array = [[NSMutableArray alloc] initWithObjects:
                                      @"facetest0989",
                                      @"facetest0988",
                                      @"facetest0987",
                                      @"facetest0986",
                                      @"facetest0985",
                                      @"facetest0984",
                                      @"facetest0983",
                                      @"facetest0982",
                                      @"facetest0981",
                                      @"facetest0980",
                                      @"facetest0979",
                                      @"facetest0978",
                                      @"facetest0977",
                                      @"facetest0976",
                                      @"facetest0975",
                                      @"facetest0974",
                                      @"facetest0973",
                                      @"facetest0972",
                                      @"facetest0971",
                                      @"facetest0970",
                                      @"facetest0969",
                                      @"facetest0968",
                                      @"facetest0967",
                                      @"facetest0966",
                                      @"facetest0965",
                                      @"facetest0964",
                                      @"facetest0963",
                                      @"facetest0962",
                                      @"facetest0961",
                                      @"facetest0960",
                                      @"facetest0959",
                                      @"facetest0958",
                                      @"facetest0957",
                                      @"facetest0956",
                                      @"facetest0955",
                                      @"facetest0954",
                                      @"facetest0953",
                                      @"facetest0952",
                                      @"facetest0951",
                                      @"facetest0950",
                                      @"facetest0949",
                                      @"facetest0948",
                                      @"facetest0947",
                                      @"facetest0946",
                                      @"facetest0945",
                                      @"facetest0944",
                                      @"facetest0943",
                                      @"facetest0942",
                                      @"facetest0941",
                                      @"facetest0940",
                                      @"facetest0939",
                                      @"facetest0938",
                                      @"facetest0937",
                                      @"facetest0936",
                                      @"facetest0935",
                                      @"facetest0934",
                                      @"facetest0933",
                                      @"facetest0932",
                                      @"facetest0931",
                                      @"facetest0930",
                                      @"facetest0929",
                                      @"facetest0928",
                                      @"facetest0927",
                                      @"facetest0926",
                                      @"facetest0925",
                                      @"facetest0924",
                                      @"facetest0923",
                                      @"facetest0922",
                                      @"facetest0921",
                                      @"facetest0920",
                                      @"facetest0919",
                                      @"facetest0918",
                                      @"facetest0917",
                                      @"facetest0916",
                                      @"facetest0915",
                                      @"facetest0914",
                                      @"facetest0913",
                                      @"facetest0912",
                                      @"facetest0911",
                                      @"facetest0910",
                                      @"facetest0909",
                                      @"facetest0908",
                                      @"facetest0907",
                                      @"facetest0906",
                                      @"facetest0905",
                                      @"facetest0904",
                                      @"facetest0903",
                                      @"facetest0902",
                                      @"facetest0901",
                                      @"facetest0900",
                                      @"facetest0899",
                                      @"facetest0898",
                                      @"facetest0897",
                                      @"facetest0896",
                                      @"facetest0895",
                                      @"facetest0894",
                                      @"facetest0893",
                                      @"facetest0892",
                                      @"facetest0891",
                                      @"facetest0890",
                                      @"facetest0889",
                                      @"facetest0888",
                                      @"facetest0887",
                                      @"facetest0886",
                                      @"facetest0885",
                                      @"facetest0884",
                                      @"facetest0883",
                                      @"facetest0882",
                                      @"facetest0881",
                                      @"facetest0880",
                                      @"facetest0879",
                                      @"facetest0878",
                                      @"facetest0877",
                                      @"facetest0876",
                                      @"facetest0875",
                                      @"facetest0874",
                                      @"facetest0873",
                                      @"facetest0872",
                                      @"facetest0871",
                                      @"facetest0870",
                                      @"facetest0869",
                                      @"facetest0868",
                                      @"facetest0867",
                                      @"facetest0866",
                                      @"facetest0865",
                                      @"facetest0864",
                                      @"facetest0863",
                                      @"facetest0862",
                                      @"facetest0861",
                                      @"facetest0860",
                                      @"facetest0859",
                                      @"facetest0858",
                                      @"facetest0857",
                                      @"facetest0856",
                                      @"facetest0855",
                                      @"facetest0854",
                                      @"facetest0853",
                                      @"facetest0852",
                                      @"facetest0851",
                                      @"facetest0850",
                                      @"facetest0849",
                                      @"facetest0874",
                                      @"facetest0873",
                                      @"facetest0872",
                                      @"facetest0871",
                                      @"facetest0870",
                                      @"facetest0869",
                                      @"facetest0868",
                                      @"facetest0867",
                                      @"facetest0866",
                                      @"facetest0865",
                                      @"facetest0864",
                                      @"facetest0863",
                                      @"facetest0862",
                                      @"facetest0861",
                                      @"facetest0860",
                                      @"facetest0859",
                                      @"facetest0959",
                                      @"facetest0960",
                                      @"facetest0961",
                                      @"facetest0962",
                                      @"facetest0963",
                                      @"facetest0964",
                                      @"facetest0965",
                                      @"facetest0966",
                                      @"facetest0967",
                                      @"facetest0968",
                                      @"facetest0969",
                                      @"facetest0970",
                                      @"facetest0971",
                                      @"facetest0972",
                                      @"facetest0973",
                                      @"facetest0974",
                                      @"facetest0975",
                                      @"facetest0976",
                                      @"facetest0977",
                                      @"facetest0978",
                                      @"facetest0979",
                                      @"facetest0980",
                                      @"facetest0981",
                                      @"facetest0982",
                                      @"facetest0983",
                                      @"facetest0984",
                                      @"facetest0985",
                                      @"facetest0986",
                                      @"facetest0987",
                                      @"facetest0988",
                                      @"facetest0989",
                                      nil];
    exercise6.animationImages = exercise6array;
    exercise6.animationDuration = 7.52;
    exercise6.animationRepeatCount = 1;
    exercise6array = nil;
    
    //Exercise 7 Array
    NSMutableArray *exercise7array = [[NSMutableArray alloc] initWithObjects:
                                      @"facetest0999",
                                      @"facetest1000",
                                      @"facetest1001",
                                      @"facetest1002",
                                      @"facetest1003",
                                      @"facetest1004",
                                      @"facetest1005",
                                      @"facetest1006",
                                      @"facetest1007",
                                      @"facetest1008",
                                      @"facetest1009",
                                      @"facetest1010",
                                      @"facetest1011",
                                      @"facetest1012",
                                      @"facetest1013",
                                      @"facetest1014",
                                      @"facetest1015",
                                      @"facetest1016",
                                      @"facetest1017",
                                      @"facetest1018",
                                      @"facetest1019",
                                      @"facetest1020",
                                      @"facetest1021",
                                      @"facetest1022",
                                      @"facetest1023",
                                      @"facetest1024",
                                      @"facetest1025",
                                      @"facetest1026",
                                      @"facetest1027",
                                      @"facetest1028",
                                      @"facetest1029",
                                      @"facetest1030",
                                      @"facetest1031",
                                      @"facetest1032",
                                      @"facetest1033",
                                      @"facetest1034",
                                      @"facetest1035",
                                      @"facetest1036",
                                      @"facetest1037",
                                      @"facetest1038",
                                      @"facetest1039",
                                      @"facetest1040",
                                      @"facetest1041",
                                      @"facetest1042",
                                      @"facetest1043",
                                      @"facetest1044",
                                      @"facetest1045",
                                      @"facetest1046",
                                      @"facetest1047",
                                      @"facetest1048",
                                      @"facetest1049",
                                      @"facetest1050",
                                      @"facetest1051",
                                      @"facetest1052",
                                      @"facetest1053",
                                      @"facetest1054",
                                      @"facetest1055",
                                      @"facetest1056",
                                      @"facetest1057",
                                      @"facetest1058",
                                      @"facetest1059",
                                      @"facetest1060",
                                      @"facetest1061",
                                      @"facetest1062",
                                      @"facetest1063",
                                      @"facetest1064",
                                      @"facetest1065",
                                      @"facetest1066",
                                      @"facetest1067",
                                      @"facetest1068",
                                      @"facetest1069",
                                      @"facetest1070",
                                      @"facetest1071",
                                      @"facetest1072",
                                      @"facetest1073",
                                      @"facetest1074",
                                      @"facetest1075",
                                      @"facetest1076",
                                      @"facetest1077",
                                      @"facetest1078",
                                      @"facetest1079",
                                      @"facetest1080",
                                      @"facetest1081",
                                      @"facetest1082",
                                      @"facetest1083",
                                      @"facetest1084",
                                      @"facetest1085",
                                      @"facetest1086",
                                      @"facetest1087",
                                      @"facetest1088",
                                      @"facetest1089",
                                      @"facetest1090",
                                      @"facetest1091",
                                      @"facetest1092",
                                      @"facetest1093",
                                      @"facetest1094",
                                      @"facetest1095",
                                      @"facetest1096",
                                      @"facetest1097",
                                      @"facetest1098",
                                      @"facetest1099",
                                      @"facetest1100",
                                      @"facetest1101",
                                      @"facetest1102",
                                      @"facetest1103",
                                      @"facetest1104",
                                      @"facetest1105",
                                      @"facetest1106",
                                      @"facetest1107",
                                      @"facetest1108",
                                      @"facetest1109",
                                      @"facetest1110",
                                      @"facetest1111",
                                      @"facetest1112",
                                      @"facetest1113",
                                      @"facetest1114",
                                      @"facetest1115",
                                      @"facetest1116",
                                      @"facetest1117",
                                      @"facetest1118",
                                      @"facetest1119",
                                      @"facetest1120",
                                      @"facetest1121",
                                      @"facetest1122",
                                      @"facetest1123",
                                      @"facetest1124",
                                      @"facetest1125",
                                      @"facetest1126",
                                      @"facetest1127",
                                      @"facetest1128",
                                      @"facetest1129",
                                      @"facetest1130",
                                      @"facetest1131",
                                      @"facetest1132",
                                      @"facetest1133",
                                      @"facetest1134",
                                      @"facetest1135",
                                      @"facetest1136",
                                      @"facetest1137",
                                      @"facetest1138",
                                      @"facetest1139",
                                      @"facetest1140",
                                      @"facetest1141",
                                      @"facetest1142",
                                      @"facetest1143",
                                      @"facetest1144",
                                      @"facetest1145",
                                      @"facetest1146",
                                      @"facetest1147",
                                      @"facetest1148",
                                      @"facetest1149",
                                      @"facetest1024",
                                      @"facetest1023",
                                      @"facetest1022",
                                      @"facetest1021",
                                      @"facetest1020",
                                      @"facetest1019",
                                      @"facetest1018",
                                      @"facetest1017",
                                      @"facetest1016",
                                      @"facetest1015",
                                      @"facetest1014",
                                      @"facetest1013",
                                      @"facetest1012",
                                      @"facetest1011",
                                      @"facetest1010",
                                      @"facetest1009",
                                      @"facetest1008",
                                      @"facetest1007",
                                      @"facetest1006",
                                      @"facetest1005",
                                      @"facetest1004",
                                      @"facetest1003",
                                      @"facetest1002",
                                      @"facetest1001",
                                      @"facetest1000",
                                      @"facetest0999",
                                      nil];
    exercise7.animationImages = exercise7array;
    exercise7.animationDuration = 7.08;
    exercise7.animationRepeatCount = 1;
    exercise7array = nil;
 
    //Exercise 8 Array
    NSMutableArray *exercise8array = [[NSMutableArray alloc] initWithObjects:
                                      @"frown0001",
                                      @"frown0002",
                                      @"frown0003",
                                      @"frown0004",
                                      @"frown0005",
                                      @"frown0006",
                                      @"frown0007",
                                      @"frown0008",
                                      @"frown0009",
                                      @"frown0010",
                                      @"frown0011",
                                      @"frown0012",
                                      @"frown0013",
                                      @"frown0014",
                                      @"frown0015",
                                      @"frown0016",
                                      @"frown0017",
                                      @"frown0018",
                                      @"frown0019",
                                      @"frown0020",
                                      @"frown0021",
                                      @"frown0022",
                                      @"frown0023",
                                      @"frown0024",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0025",
                                      @"frown0026",
                                      @"frown0027",
                                      @"frown0028",
                                      @"frown0029",
                                      @"frown0030",
                                      @"frown0031",
                                      @"frown0032",
                                      @"frown0033",
                                      @"frown0034",
                                      @"frown0035",
                                      @"frown0036",
                                      @"frown0037",
                                      @"frown0038",
                                      @"frown0039",
                                      @"frown0040",
                                      @"frown0041",
                                      @"frown0042",
                                      @"frown0043",
                                      @"frown0044",
                                      @"frown0045",
                                      @"frown0046",
                                      @"frown0047",
                                      @"frown0048",
                                      @"frown0049",
                                      @"frown0050",
                                      nil];
    exercise8.animationImages = exercise8array;
    exercise8.animationDuration = 7.0;
    exercise8.animationRepeatCount = 1;
    exercise8array = nil;

    //Exercise 9 Array
    NSMutableArray *exercise9array = [[NSMutableArray alloc] initWithObjects:
                                      @"facetest1473",
                                      @"facetest1472",
                                      @"facetest1471",
                                      @"facetest1470",
                                      @"facetest1469",
                                      @"facetest1468",
                                      @"facetest1467",
                                      @"facetest1466",
                                      @"facetest1465",
                                      @"facetest1464",
                                      @"facetest1463",
                                      @"facetest1462",
                                      @"facetest1461",
                                      @"facetest1460",
                                      @"facetest1459",
                                      @"facetest1458",
                                      @"facetest1457",
                                      @"facetest1456",
                                      @"facetest1455",
                                      @"facetest1454",
                                      @"facetest1453",
                                      @"facetest1452",
                                      @"facetest1451",
                                      @"facetest1450",
                                      @"facetest1449",
                                      @"facetest1448",
                                      @"facetest1447",
                                      @"facetest1446",
                                      @"facetest1445",
                                      @"facetest1444",
                                      @"facetest1443",
                                      @"facetest1442",
                                      @"facetest1441",
                                      @"facetest1440",
                                      @"facetest1439",
                                      @"facetest1438",
                                      @"facetest1437",
                                      @"facetest1436",
                                      @"facetest1435",
                                      @"facetest1434",
                                      @"facetest1433",
                                      @"facetest1432",
                                      @"facetest1431",
                                      @"facetest1430",
                                      @"facetest1429",
                                      @"facetest1428",
                                      @"facetest1427",
                                      @"facetest1426",
                                      @"facetest1425",
                                      @"facetest1424",
                                      @"facetest1423",
                                      @"facetest1422",
                                      @"facetest1421",
                                      @"facetest1420",
                                      @"facetest1419",
                                      @"facetest1418",
                                      @"facetest1417",
                                      @"facetest1416",
                                      @"facetest1415",
                                      @"facetest1414",
                                      @"facetest1413",
                                      @"facetest1412",
                                      @"facetest1411",
                                      @"facetest1410",
                                      @"facetest1409",
                                      @"facetest1408",
                                      @"facetest1407",
                                      @"facetest1406",
                                      @"facetest1405",
                                      @"facetest1404",
                                      @"facetest1403",
                                      @"facetest1402",
                                      @"facetest1401",
                                      @"facetest1400",
                                      @"facetest1399",
                                      @"facetest1398",
                                      @"facetest1397",
                                      @"facetest1396",
                                      @"facetest1395",
                                      @"facetest1394",
                                      @"facetest1393",
                                      @"facetest1392",
                                      @"facetest1391",
                                      @"facetest1390",
                                      @"facetest1389",
                                      @"facetest1388",
                                      @"facetest1387",
                                      @"facetest1386",
                                      @"facetest1385",
                                      @"facetest1384",
                                      @"facetest1383",
                                      @"facetest1382",
                                      @"facetest1381",
                                      @"facetest1380",
                                      @"facetest1379",
                                      @"facetest1378",
                                      @"facetest1377",
                                      @"facetest1376",
                                      @"facetest1375",
                                      @"facetest1374",
                                      @"facetest1373",
                                      @"facetest1372",
                                      @"facetest1371",
                                      @"facetest1370",
                                      @"facetest1369",
                                      @"facetest1368",
                                      @"facetest1367",
                                      @"facetest1366",
                                      @"facetest1365",
                                      @"facetest1364",
                                      @"facetest1363",
                                      @"facetest1362",
                                      @"facetest1361",
                                      @"facetest1360",
                                      @"facetest1359",
                                      @"facetest1358",
                                      @"facetest1357",
                                      @"facetest1356",
                                      @"facetest1355",
                                      @"facetest1354",
                                      @"facetest1353",
                                      @"facetest1352",
                                      @"facetest1351",
                                      @"facetest1350",
                                      @"facetest1349",
                                      @"facetest1348",
                                      @"facetest1347",
                                      @"facetest1346",
                                      @"facetest1345",
                                      @"facetest1344",
                                      @"facetest1343",
                                      @"facetest1342",
                                      @"facetest1341",
                                      @"facetest1340",
                                      @"facetest1339",
                                      @"facetest1338",
                                      @"facetest1337",
                                      @"facetest1336",
                                      @"facetest1335",
                                      @"facetest1334",
                                      @"facetest1333",
                                      @"facetest1332",
                                      @"facetest1331",
                                      @"facetest1330",
                                      @"facetest1329",
                                      @"facetest1328",
                                      @"facetest1327",
                                      @"facetest1326",
                                      @"facetest1325",
                                      @"facetest1324",
                                      @"facetest1449",
                                      @"facetest1450",
                                      @"facetest1451",
                                      @"facetest1452",
                                      @"facetest1453",
                                      @"facetest1454",
                                      @"facetest1455",
                                      @"facetest1456",
                                      @"facetest1457",
                                      @"facetest1458",
                                      @"facetest1459",
                                      @"facetest1460",
                                      @"facetest1461",
                                      @"facetest1462",
                                      @"facetest1463",
                                      @"facetest1464",
                                      @"facetest1465",
                                      @"facetest1466",
                                      @"facetest1467",
                                      @"facetest1468",
                                      @"facetest1469",
                                      @"facetest1470",
                                      @"facetest1471",
                                      @"facetest1472",
                                      @"facetest1473",
                                      nil];
    exercise9.animationImages = exercise9array;
    exercise9.animationDuration = 8.08;
    exercise9.animationRepeatCount = 1;
    exercise9array = nil;
    
}

- (void) exercise1Button:(id)sender {
    [exercise1 startAnimating];
}

- (void) exercise2Button:(id)sender {
    [exercise2 startAnimating];
}

- (void) exercise3Button:(id)sender {
    [exercise3 startAnimating];
}

- (void) exercise4Button:(id)sender {
    [exercise4 startAnimating];
}

- (void) exercise5Button:(id)sender {
    [exercise5 startAnimating];
}

- (void) exercise6Button:(id)sender {
    [exercise6 startAnimating];
}

- (void) exercise7Button:(id)sender {
    [exercise7 startAnimating];
}

- (void) exercise8Button:(id)sender {
    [exercise8 startAnimating];
}

- (void) exercise9Button:(id)sender {
    [exercise9 startAnimating];
}


- (void)viewDidUnload
{
    [super viewDidUnload];
    self.exercise1 = nil;
    self.exercise2Button = nil;
    self.exercise2 = nil;
    self.exercise3Button = nil;
    self.exercise3 = nil;
    self.exercise4Button = nil;
    self.exercise4 = nil;
    self.exercise5Button = nil;
    self.exercise5 = nil;
   
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
}

- (void)viewWillDisappear:(BOOL)animated
{
	[super viewWillDisappear:animated];
}

- (void)viewDidDisappear:(BOOL)animated
{
	[super viewDidDisappear:animated];
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    // Return YES for supported orientations
    return (interfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
}

//Exercise info
- (IBAction)informationAlert:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Smile Big" message:@"Try to get the corners of your mouth to move towards your ears. Hold for 5 seconds." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
- (IBAction)informationAlert2:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Pucker Up" message:@"Pucker your lips like you're drinking from a straw. Hold tightly for 5 seconds." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
- (IBAction)informationAlert3:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Side To Side" message:@"Hold your lips together and move them from side to side. You should feel the stretch in your cheeks." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
- (IBAction)informationAlert4:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Fill Your Cheeks" message:@"Fill your cheeks with air. Hold for 5 seconds." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
- (IBAction)informationAlert5:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Fish Face" message:@"Make a Fish Face, suck in your cheeks with your lips puckered. Hold for 5 seconds." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
- (IBAction)informationAlert6:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Say Eeeee" message:@"With a big smile say Eeeee, then Pucker your lips and say Ooooo." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}

- (IBAction)informationAlert7:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Eyebrows Raised" message:@"Raise both eyebrows as high as you can. Hold them for 5 seconds." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
- (IBAction)informationAlert8:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Frown" message:@"Concentrate on squeezing your eyebrows together and wrinkling your forehead. Hold for 5 seconds." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
- (IBAction)informationAlert9:(id)sender {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"No Peaking" message:@"Close both eyes tightly. Hold for 5 seconds." delegate:nil cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}

- (IBAction)playExerciseSound:(id)sender {
    AudioServicesPlaySystemSound(SoundID);
}

@end


